/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lvq;

import ViewProgram.Home;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import jxl.Sheet;
import jxl.Workbook;

/**
 *
 * @author oikawa
 */
public class FrameData extends javax.swing.JFrame {

    public FrameData() {
        initComponents();
        //fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("PDF Documents", "pdf"));
        fileChooser.setFileFilter(new FileNameExtensionFilter("MS Excel Documents(*.xls, *.xlsx)", "xls", "xlsx"));
        fileChooser.setCurrentDirectory(new File("G:\\ProgramTugasAkhir"));
        ImageIcon icon = new ImageIcon(getClass().getResource("/aset/fruits.png"));
        setIconImage(icon.getImage());
        
        if (excelFile != null) {
            muatData(excelFile);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelKembali = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnSetuju = new javax.swing.JLabel();
        btnPilihData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        fileChooser.setCurrentDirectory(new java.io.File("G:\\ProgramTugasAkhir"));
        fileChooser.setDialogTitle("Pilih Data");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 830, 440));

        jPanel2.setBackground(new java.awt.Color(18, 181, 21));

        jLabel1.setBackground(new java.awt.Color(254, 254, 254));
        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Aplikasi Pengenalan Citra Buah-buahan");

        LabelKembali.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelKembali.setForeground(new java.awt.Color(254, 254, 254));
        LabelKembali.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/previous.png"))); // NOI18N
        LabelKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelKembaliMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("|");

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/icons8_home_36px.png"))); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/icons8_delete_sign2_16px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnHome)
                .addGap(4, 4, 4)
                .addComponent(jLabel17)
                .addGap(5, 5, 5)
                .addComponent(LabelKembali)
                .addGap(195, 195, 195)
                .addComponent(jLabel1)
                .addContainerGap(722, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(843, 843, 843)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(478, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHome, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 40));

        btnSetuju.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSetuju.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/btnSetuju.png"))); // NOI18N
        btnSetuju.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetujuMouseClicked(evt);
            }
        });
        jPanel1.add(btnSetuju, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        btnPilihData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/btnPilihData.png"))); // NOI18N
        btnPilihData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPilihDataMouseClicked(evt);
            }
        });
        jPanel1.add(btnPilihData, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("INISIALISASI BOBOT AWAL");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(888, 661));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetujuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetujuMouseClicked
        // TODO add your handling code here:
        if (excelFile == null) {
            JOptionPane.showMessageDialog(new JFrame(), "Harap Pilih Data !!!!!");
        } else {
            if (FrameDepan.s == null) {
                FrameDepan.s = "Data terisi";
            } else {
                String string = " lagi ...";
                FrameDepan.s += string;
            }
            System.out.println(FrameDepan.s);
            System.out.println(excelFile.toString());
            FrameDepan.path = excelFile.toString();
            FrameDepan.data.setInputFile(excelFile.toString());
            try {
                FrameDepan.data.read();
            } catch (IOException ex) {
                Logger.getLogger(FrameData.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(new JFrame(),
                    "Harap di cek lagi .... !",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
            this.dispose();
        }
        new FrameDepan().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSetujuMouseClicked

    private void btnPilihDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDataMouseClicked
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            excelFile = fileChooser.getSelectedFile();
            try {
                // Tampikan data
                muatData(excelFile);

            } catch (Exception ex) {
                System.out.println("Terdapat masalah dalam akses file " + excelFile.getAbsolutePath());
                JOptionPane.showMessageDialog(new JFrame(),
                    "Terdapat masalah dalam akses file",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        } else {
            System.out.println("Akses file dibatalkan");
        }
    }//GEN-LAST:event_btnPilihDataMouseClicked

    private void LabelKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelKembaliMouseClicked
        // TODO add your handling code here:
        new FrameDepan().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LabelKembaliMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this,
             "Apakah Anda yakin ingin menutup Aplikasi ini? ",  "Tutup Aplikasi? ",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void muatData(File file) {
        File excelFile = file;

        // buat model untuk file excel
        if (excelFile.exists()) {
            try {
                Workbook workbook = Workbook.getWorkbook(excelFile);
                Sheet sheet = workbook.getSheets()[0];

                TableModel model = new DefaultTableModel(sheet.getRows() - 1, sheet.getColumns());
                for (int row = 0; row < model.getRowCount(); row++) {
                    for (int column = 0; column < model.getColumnCount(); column++) {
                        String content = sheet.getCell(column, row + 1).getContents();
                        model.setValueAt(content, row, column);
                    }
                }
                Object[] columnNames = new Object[sheet.getColumns()];
                for (int i = 0; i < sheet.getColumns(); i++) {
                    columnNames[i] = sheet.getCell(i, 0).getContents();
                }

                table.setModel(model);
                JTableHeader th = table.getTableHeader();
                TableColumnModel tcm = th.getColumnModel();
                TableColumn tc;
                for (int i = 0; i < tcm.getColumnCount(); i++) {
                    tc = tcm.getColumn(i);
                    tc.setHeaderValue(columnNames[i]);
                }

                th.repaint();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e);
            }

        } else {
            JOptionPane.showMessageDialog(null, "File does not exist");
        }
    }

    //variables
    public FrameDepan frDepan = null;
    static File excelFile = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelKembali;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnPilihData;
    private javax.swing.JLabel btnSetuju;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
