/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lvq;

import ViewProgram.Home;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import jxl.Sheet;
import jxl.Workbook;

/**
 *
 * @author oikawa
 */
public class FrameLvq extends javax.swing.JFrame {

    public FrameLvq() {
        initComponents();
        fileChooser.setFileFilter(new FileNameExtensionFilter("MS Excel Documents(*.xls, *.xlsx)", "xls", "xlsx"));
        fileChooser.setCurrentDirectory(new File("G:\\ProgramTugasAkhir"));
        path = FrameDepan.path;
        ImageIcon icon = new ImageIcon(getClass().getResource("/aset/fruits.png"));
        setIconImage(icon.getImage());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataLatihTable = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        minLearningRtTextField = new javax.swing.JTextField();
        decLearningRtTextField = new javax.swing.JTextField();
        learningRateTextField = new javax.swing.JTextField();
        epohTextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnHome2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        LabelKembali = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnPilihDataLatih = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hasilTable1 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        masukPengujianButton = new javax.swing.JButton();
        lihatGrafikButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labeEror = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labeLRate = new javax.swing.JLabel();
        waktuPelatihanLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labeJumlahData = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        fileChooser.setCurrentDirectory(new java.io.File("G:\\ProgramTugasAkhir"));
        fileChooser.setDialogTitle("Pilih Data");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LVQ Pelatihan");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PELATIHAN LEARNING VECTOR QUANTIZATON");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Data Latih");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 78, 19));

        dataLatihTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataLatihTable.setEnabled(false);
        jScrollPane1.setViewportView(dataLatihTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 560, 280));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 850, 10));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Banyak Iterasi/epoh");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 448, 190, 30));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Learning Rate");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 488, 190, 30));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Pengurangan Learning Rate");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 180, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Minimum Learning Rate ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 180, 30));

        minLearningRtTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        minLearningRtTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                minLearningRtTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(minLearningRtTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, 160, 28));

        decLearningRtTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        decLearningRtTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                decLearningRtTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(decLearningRtTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 160, 28));

        learningRateTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        learningRateTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                learningRateTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(learningRateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 160, 28));

        epohTextField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        epohTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epohTextFieldActionPerformed(evt);
            }
        });
        epohTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                epohTextFieldKeyTyped(evt);
            }
        });
        jPanel1.add(epohTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 160, 28));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 820, 10));

        jPanel2.setBackground(new java.awt.Color(18, 181, 21));

        jLabel9.setBackground(new java.awt.Color(254, 254, 254));
        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Aplikasi Pengenalan Citra Buah-buahan");

        btnHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/icons8_home_36px.png"))); // NOI18N
        btnHome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHome2MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("|");

        LabelKembali.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelKembali.setForeground(new java.awt.Color(254, 254, 254));
        LabelKembali.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/previous.png"))); // NOI18N
        LabelKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelKembaliMouseClicked(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/icons8_delete_sign2_16px.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(13, 13, 13)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnHome2)
                .addGap(4, 4, 4)
                .addComponent(jLabel17)
                .addGap(5, 5, 5)
                .addComponent(LabelKembali)
                .addGap(166, 166, 166)
                .addComponent(jLabel9)
                .addGap(205, 205, 205)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(506, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHome2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 40));

        btnPilihDataLatih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/btnPilihData.png"))); // NOI18N
        btnPilihDataLatih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPilihDataLatihMouseClicked(evt);
            }
        });
        jPanel1.add(btnPilihDataLatih, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/btnLatih.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 150, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        hasilTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane2.setViewportView(hasilTable1);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("TABEL HASIL PROSES PELATIHAN  ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 290, 340));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        masukPengujianButton.setBackground(new java.awt.Color(81, 181, 21));
        masukPengujianButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        masukPengujianButton.setForeground(new java.awt.Color(255, 255, 255));
        masukPengujianButton.setText("MASUK PENGUJIAN");
        masukPengujianButton.setBorder(null);
        masukPengujianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukPengujianButtonActionPerformed(evt);
            }
        });

        lihatGrafikButton.setBackground(new java.awt.Color(255, 170, 1));
        lihatGrafikButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lihatGrafikButton.setForeground(new java.awt.Color(255, 255, 255));
        lihatGrafikButton.setText("LIHAT GRAFIK");
        lihatGrafikButton.setBorder(null);
        lihatGrafikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatGrafikButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Error :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Hasil Pelatihan");

        labeEror.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        labeEror.setForeground(new java.awt.Color(204, 0, 51));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Learning Rate Akhir :");

        labeLRate.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        labeLRate.setForeground(new java.awt.Color(51, 255, 0));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Waktu Pelatihan :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Jumlah Data :");

        labeJumlahData.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        labeJumlahData.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labeLRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labeJumlahData, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labeEror, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(waktuPelatihanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(masukPengujianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lihatGrafikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 55, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(labeJumlahData, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labeEror, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(waktuPelatihanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labeLRate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(lihatGrafikButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masukPengujianButton)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 310, 210));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/ket.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("KETERANGAN :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(865, 702));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void epohTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epohTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_epohTextFieldActionPerformed

    private void epohTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_epohTextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            System.out.println(true);
            evt.consume();
        }


    }//GEN-LAST:event_epohTextFieldKeyTyped

    private void learningRateTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_learningRateTextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!(c == '.')) {
            if (!Character.isDigit(c)) {
                System.out.println(true);
                evt.consume();
            }

        }
    }//GEN-LAST:event_learningRateTextFieldKeyTyped

    private void decLearningRtTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_decLearningRtTextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!(c == '.')) {
            if (!Character.isDigit(c)) {
                System.out.println(true);
                evt.consume();
            }

        }
    }//GEN-LAST:event_decLearningRtTextFieldKeyTyped

    private void minLearningRtTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minLearningRtTextFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!(c == '.')) {
            if (!Character.isDigit(c)) {
                System.out.println(true);
                evt.consume();
            }

        }
    }//GEN-LAST:event_minLearningRtTextFieldKeyTyped

    private void masukPengujianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukPengujianButtonActionPerformed
        // TODO add your handling code here:
        lvqUji = new FrameLvqUji();
        lvqUji.path = path;
        lvqUji.lvq = lvq;
        lvqUji.setVisible(true);
    }//GEN-LAST:event_masukPengujianButtonActionPerformed

    private void lihatGrafikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatGrafikButtonActionPerformed
        // TODO add your handling code here:
        lvq.tampilkanGrafikPelatihan();
    }//GEN-LAST:event_lihatGrafikButtonActionPerformed

    private void btnHome2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHome2MouseClicked
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHome2MouseClicked

    private void LabelKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelKembaliMouseClicked
        // TODO add your handling code here:
        new FrameDepan().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LabelKembaliMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        if (JOptionPane.showConfirmDialog(this,
                     "Apakah Anda yakin ingin menutup Aplikasi ini? ",  "Tutup Aplikasi? ",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void btnPilihDataLatihMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihDataLatihMouseClicked
         // TODO add your handling code here:

        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            excelFile = fileChooser.getSelectedFile();
            dataLatih = new DataManagement();
            try {
                // Tampikan data
                muatData(excelFile);
                dataLatih.setInputFile(excelFile.toString());
                dataLatih.read2();
                dataLatih.normalisasi();
                System.out.println("Max" + dataLatih.getDataTertinggi()[1]);
                System.out.println("Min " + dataLatih.getDataTerendah()[1]);
            } catch (Exception ex) {
                System.out.println("Terdapat masalah dalam akses file " + excelFile.getAbsolutePath());
                System.out.println(ex.getCause());
            }
        } else {
            System.out.println("Akses file dibatalkan");
        }
    }//GEN-LAST:event_btnPilihDataLatihMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        try {
            lvq = new LVQ(path);

            int banyakEpoh = Integer.valueOf(epohTextField.getText());
            double learningR = Double.valueOf(learningRateTextField.getText());
            double decLearningR = Double.valueOf(decLearningRtTextField.getText());
            double minLearningR = Double.valueOf(minLearningRtTextField.getText());
            LoaderProcess loader = new LoaderProcess(this);
            loader.execute();
            lvq.train(dataLatih, banyakEpoh, learningR, decLearningR, minLearningR);
            loader.done();
            waktuPelatihanLabel.setText(String.valueOf(loader.lamaWaktu) + " detik");
            waktuPelatihanLabel.setForeground(Color.GREEN);
            //hasilPelatihan();
            viewData();

        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(new JFrame(),
                "Harap di cek lagi .... !",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void muatData(File file) {
        File excelFile = file;

        // buat model untuk file excel
        if (excelFile.exists()) {
            try {
                Workbook workbook = Workbook.getWorkbook(excelFile);
                Sheet sheet = workbook.getSheets()[0];

                TableModel model = new DefaultTableModel(sheet.getRows() - 1, sheet.getColumns());
                for (int row = 0; row < model.getRowCount(); row++) {
                    for (int column = 0; column < model.getColumnCount(); column++) {
                        String content = sheet.getCell(column, row + 1).getContents();
                        model.setValueAt(content, row, column);
                    }
                }
                Object[] columnNames = new Object[sheet.getColumns()];
                for (int i = 0; i < sheet.getColumns(); i++) {
                    columnNames[i] = sheet.getCell(i, 0).getContents();
                }

                dataLatihTable.setModel(model);
                JTableHeader th = dataLatihTable.getTableHeader();
                TableColumnModel tcm = th.getColumnModel();
                TableColumn tc;
                for (int i = 0; i < tcm.getColumnCount(); i++) {
                    tc = tcm.getColumn(i);
                    tc.setHeaderValue(columnNames[i]);
                }

                th.repaint();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e);
            }

        } else {
            JOptionPane.showMessageDialog(null, "File does not exist");
        }
    }
    String h1, h2, h3;
    
    private void viewData(){
        labeEror.setText(lvq.logErrorPelatihan.get(lvq.logErrorPelatihan.size()-1).toString());
        labeLRate.setText(String.valueOf(lvq.learningRateAhir));
        labeJumlahData.setText(String.valueOf(lvq.jumlahdata));
        //jLabel20.setText(String.valueOf(lvq.akurasiLatih));
        try{
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No");
            model.addColumn("Jenis Buah");
            model.addColumn("Prediksi");
            //model.addColumn("Nama Buah");
            model.addColumn("Validasi");
            hasilTable1.setModel(model);
            int size = lvq.hasilLatih.length;
            int i = 0;
            while (i < size){
                model.addRow(new Object[]{
                    i+1,
                    
                    lvq.hasilLatih[i][0],
                    lvq.hasilLatih[i][1],
                    //lvq.hasilLatihValidasi[i][0],
                    lvq.hasilLatihValidasi[i][1]          
                });
                hasilTable1.setModel(model);
                i++;            
            }
        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(new JFrame(),
                "Harap di cek lagi .... !",
                "Error "+ex,
             JOptionPane.ERROR_MESSAGE);
        }      
    }
    
    
    private void hasilPelatihan() {
        //errorTextField.setText(lvq.logErrorPelatihan.get(lvq.logErrorPelatihan.size() - 1).toString());
        labeEror.setText(lvq.logErrorPelatihan.get(lvq.logErrorPelatihan.size()-1).toString());
        labeLRate.setText(String.valueOf(lvq.learningRateAhir));
        labeJumlahData.setText(String.valueOf(lvq.jumlahdata));
        try{
            
           /* DefaultTableModel model = new DefaultTableModel(lvq.hasil1.length, 3);            
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    if (j == 0) {
                        model.setValueAt(i + 1, i, 0);
                    } else {
                        if (lvq.hasil1[i][0] == lvq.hasil1[i][1]) {
                            model.setValueAt(lvq.hasil1[i][j - 1], i, j);
                            if (lvq.hasil1[i][0]==0) {
                                h1="Apel";
                                System.out.println(h1);
                            }else if (lvq.hasil1[i][0]==1) {
                                h2="Jeruk";
                                System.out.println(h2);
                            }else{
                                h3="Pisang";
                                System.out.println(h3);
                            }
                        }else {
                            model.setValueAt(lvq.hasil1[i][j - 1]+ "", i, j);
                            if (lvq.hasil1[i][0]==0) {
                                h1="Apel";
                                System.out.println(h1);
                            }else if (lvq.hasil1[i][0]==1) {
                                h2="Jeruk";
                                System.out.println(h2);
                            }else{
                                h3="Pisang";
                                System.out.println(h3);
                            }
                        }
                    }
                }
                
            }

            hasilTable1.setModel(model);
            JTableHeader th = hasilTable1.getTableHeader();
            TableColumnModel tcm = th.getColumnModel();
            TableColumn tc = tcm.getColumn(0);
            tc.setHeaderValue("No");
            tc = tcm.getColumn(1);
            tc.setHeaderValue("Data Aktual");
            tc = tcm.getColumn(2);
            tc.setHeaderValue("Hasil Prediksi");*/
           
           viewData();
           /*
            TableModel model = new DefaultTableModel(lvq.hasil1.length, 5);
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    if (j == 0) {
                        model.setValueAt(i + 1, i, 0);
                    } else {
                        if (lvq.hasil1[i][0] == lvq.hasil1[i][1]) {
                            model.setValueAt(lvq.hasil1[i][j - 1], i, j);
                        }else {
                            model.setValueAt(lvq.hasil1[i][j - 1] + "", i, j);
                        }
                    }

                }
            }
            hasilTable1.setModel(model);
            JTableHeader th = hasilTable1.getTableHeader();
            TableColumnModel tcm = th.getColumnModel();
            TableColumn tc = tcm.getColumn(0);
            tc.setHeaderValue("No");
            tc = tcm.getColumn(1);
            tc.setHeaderValue("Jenis Buah");
            tc = tcm.getColumn(2);
            tc.setHeaderValue("Prediksi");
            tc = tcm.getColumn(3);
            tc.setHeaderValue("Nama Buah");
            tc = tcm.getColumn(4);
            tc.setHeaderValue("Validasi");
            tc = tcm.getColumn(5);
            th.repaint();*/
           
           
        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(new JFrame(),
                "Harap di cek lagi .... !",
                "Error "+ex,
                JOptionPane.ERROR_MESSAGE);
      }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLvq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLvq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLvq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLvq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLvq().setVisible(true);
            }
        });
    }

    File excelFile = null;
    LVQ lvq;
    String path;
    DataManagement dataLatih;
    FrameLvqUji lvqUji;
   
    public FrameDepan frDepan;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelKembali;
    private javax.swing.JLabel btnHome2;
    private javax.swing.JLabel btnPilihDataLatih;
    private javax.swing.JTable dataLatihTable;
    private javax.swing.JTextField decLearningRtTextField;
    private javax.swing.JTextField epohTextField;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTable hasilTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labeEror;
    private javax.swing.JLabel labeJumlahData;
    private javax.swing.JLabel labeLRate;
    private javax.swing.JTextField learningRateTextField;
    private javax.swing.JButton lihatGrafikButton;
    private javax.swing.JButton masukPengujianButton;
    private javax.swing.JTextField minLearningRtTextField;
    private javax.swing.JLabel waktuPelatihanLabel;
    // End of variables declaration//GEN-END:variables

}
